using System;

namespace Gerontocracy.App.Models.Board
{
    /// <summary>
    /// A thread to a topic
    /// </summary>
    public class ThreadOverview
    {
        /// <summary>
        /// The identifier of the thread
        /// </summary>
        public long Id { get; set; }

        /// <summary>
        /// Title
        /// </summary>
        public string Titel { get; set; }

        /// <summary>
        /// Affair Id
        /// </summary>
        public long? VorfallId { get; set; }

        /// <summary>
        /// Title of Affair
        /// </summary>
        public string VorfallTitel { get; set; }

        /// <summary>
        /// Id of politician who was involved
        /// </summary>
        public long? PolitikerId { get; set; }

        /// <summary>
        /// Name of politician who was involved
        /// </summary>
        public string PolitikerName { get; set; }
        
        /// <summary>
        /// When the post was created
        /// </summary>
        public DateTime CreatedOn { get; set; }

        /// <summary>
        /// Id of author
        /// </summary>
        public long? UserId { get; set; }

        /// <summary>
        /// Name of Author
        /// </summary>
        public string UserName { get; set; }

        /// <summary>
        /// How many posts this thread has
        /// </summary>
        public long NumPosts { get; set; }

        /// <summary>
        /// Is generated by the system
        /// </summary>
        public bool Generated { get; set; }
    }
}
